name: Update triballaw templates every 24 hrs
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NILL_SSH_KEY_LAW }}" > ~/.ssh/id_ed25519_law
          echo "${{ secrets.NILL_SSH_KEY_HTML }}" > ~/.ssh/id_ed25519_html
          chmod 600 ~/.ssh/id_ed25519_law ~/.ssh/id_ed25519_html
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up SSH config and git credentials
        run: |
          echo "Host github.com" > ~/.ssh/config
          echo "  Hostname github.com" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ed25519_law" >> ~/.ssh/config
          echo "  StrictHostKeyChecking accept-new" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          git config --global user.name "oll-bot"
          git config --global user.email "developers@openlawlib.org"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install taf and lxml
        run: |
          python -m pip install --upgrade taf lxml==5.3.*

      - name: Set up archive directory
        run: |
          mkdir -p archive

      - name: Clone all tribes and update templates
        run: taf repo clone git@github.com:${{ github.repository }}.git
        working-directory: ./archive